import {FormEvent, useEffect, useState} from "react";
const API="http://localhost:8000";
type Farmer={id:number;farmer_id:string;name:string;gender?:string;phone?:string;county:string;sub_county?:string;ward?:string;village?:string;active:boolean};
type Animal={id:number;animal_id:string;farmer_id:number;name?:string;breed?:string;sex:string;status:string};
type Dashboard={farmers:number;animals:number;milk_litres:number;payments:number};
type Milk={id:number;farmer_id:number;record_date:string;morning_litres:number;evening_litres:number};
type Payment={id:number;farmer_id:number;week_start:string;week_end:string;litres:number;gross_amount:number;deductions:number;net_amount:number;method:string;reference?:string};

async function api(path:string, options?:RequestInit){const r=await fetch(API+path,{headers:{"Content-Type":"application/json"},...options});if(!r.ok){const e=await r.json().catch(()=>({detail:r.statusText}));throw new Error(e.detail||"Request failed");}return r.json();}

function App(){
 const [tab,setTab]=useState("dashboard"); const [farmers,setFarmers]=useState<Farmer[]>([]); const [animals,setAnimals]=useState<Animal[]>([]); const [milk,setMilk]=useState<Milk[]>([]); const [payments,setPayments]=useState<Payment[]>([]); const [dash,setDash]=useState<Dashboard>({farmers:0,animals:0,milk_litres:0,payments:0}); const [error,setError]=useState("");
 const load=async()=>{try{setError("");const [d,f,a,m,p]=await Promise.all([api("/api/dashboard"),api("/api/farmers"),api("/api/animals"),api("/api/milk-records"),api("/api/payments")]);setDash(d);setFarmers(f);setAnimals(a);setMilk(m);setPayments(p)}catch(e){setError(e instanceof Error?e.message:"Could not connect to API")}};
 useEffect(()=>{load()},[]);
 return <main className="app"><header><div><b>DAIRY LINK</b><span>Digital Dairy Value-Chain Platform</span></div><small>MVP v0.2</small></header>
 <nav>{["dashboard","farmers","animals","milk","payments"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
 {error&&<div className="error">{error}. Start the FastAPI backend and PostgreSQL database.</div>}
 {tab==="dashboard"&&<Dashboard dash={dash} farmers={farmers} milk={milk} payments={payments}/>}
 {tab==="farmers"&&<Farmers farmers={farmers} reload={load}/>}
 {tab==="animals"&&<Animals farmers={farmers} animals={animals} reload={load}/>}
 {tab==="milk"&&<MilkPage farmers={farmers} milk={milk} reload={load}/>}
 {tab==="payments"&&<Payments farmers={farmers} payments={payments} reload={load}/>}
 </main>
}

function Dashboard({dash,farmers,milk,payments}:{dash:Dashboard;farmers:Farmer[];milk:Milk[];payments:Payment[]}){
 return <><section className="hero"><h1>Dairy Link Dashboard</h1><p>Core farmer, animal, milk and payment workflows.</p></section><section className="cards"><Card t="Farmers" v={dash.farmers}/><Card t="Animals" v={dash.animals}/><Card t="Milk Recorded" v={`${dash.milk_litres.toFixed(1)} L`}/><Card t="Net Payments" v={`KES ${dash.payments.toFixed(0)}`}/></section><section className="panel"><h2>Recent Farmers</h2><Table headers={["Farmer ID","Name","County","Ward","Status"]} rows={farmers.slice(0,8).map(f=>[f.farmer_id,f.name,f.county,f.ward||"—",f.active?"Active":"Inactive"])}/></section></>
}
function Card({t,v}:{t:string;v:string|number}){return <div className="card"><span>{t}</span><strong>{v}</strong></div>}

function Farmers({farmers,reload}:{farmers:Farmer[];reload:()=>void}){
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/farmers",{method:"POST",body:JSON.stringify({farmer_id:f.get("farmer_id"),name:f.get("name"),gender:f.get("gender"),phone:f.get("phone"),county:f.get("county")||"Kisii",sub_county:f.get("sub_county"),ward:f.get("ward"),village:f.get("village")})});e.currentTarget.reset();reload()}catch(err){alert(err instanceof Error?err.message:"Error")}};
 return <><section className="panel"><h2>Register Farmer</h2><form onSubmit={submit} className="form">{["farmer_id","name","phone","county","sub_county","ward","village"].map(n=><input key={n} name={n} required={["farmer_id","name"].includes(n)} maxLength={n==="farmer_id"?10:undefined} placeholder={n.replace("_"," ").toUpperCase()}/>)}<select name="gender"><option value="">Gender</option><option>Female</option><option>Male</option><option>Other</option></select><button className="primary">Save Farmer</button></form></section><section className="panel"><h2>Farmers ({farmers.length})</h2><Table headers={["ID","Name","Phone","Location","Status"]} rows={farmers.map(f=>[f.farmer_id,f.name,f.phone||"—",`${f.ward||"—"}, ${f.village||"—"}`,f.active?"Active":"Inactive"])}/></section></>
}
function Animals({farmers,animals,reload}:{farmers:Farmer[];animals:Animal[];reload:()=>void}){
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/animals",{method:"POST",body:JSON.stringify({animal_id:f.get("animal_id"),farmer_id:Number(f.get("farmer_id")),name:f.get("name")||null,breed:f.get("breed")||null,sex:f.get("sex"),status:f.get("status")})});e.currentTarget.reset();reload()}catch(err){alert(err instanceof Error?err.message:"Error")}};
 return <><section className="panel"><h2>Register Animal</h2><form onSubmit={submit} className="form"><input name="animal_id" required placeholder="ANIMAL ID"/><select name="farmer_id" required><option value="">Select farmer</option>{farmers.map(f=><option value={f.id} key={f.id}>{f.farmer_id} — {f.name}</option>)}</select><input name="name" placeholder="Animal name"/><input name="breed" placeholder="Breed"/><select name="sex"><option>Female</option><option>Male</option></select><select name="status"><option>Lactating</option><option>Dry</option><option>In Calf</option><option>Heifer</option><option>Calf</option><option>Bull</option></select><button className="primary">Save Animal</button></form></section><section className="panel"><h2>Animals ({animals.length})</h2><Table headers={["Animal ID","Farmer","Name","Breed","Sex","Status"]} rows={animals.map(a=>[a.animal_id,farmers.find(f=>f.id===a.farmer_id)?.name||String(a.farmer_id),a.name||"—",a.breed||"—",a.sex,a.status])}/></section></>
}
function MilkPage({farmers,milk,reload}:{farmers:Farmer[];milk:Milk[];reload:()=>void}){
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/milk-records",{method:"POST",body:JSON.stringify({farmer_id:Number(f.get("farmer_id")),record_date:f.get("record_date"),morning_litres:Number(f.get("morning_litres")||0),evening_litres:Number(f.get("evening_litres")||0),collector:f.get("collector")||null})});e.currentTarget.reset();reload()}catch(err){alert(err instanceof Error?err.message:"Error")}};
 return <><section className="panel"><h2>Record Milk Collection</h2><p className="hint">Enter 0 for a session when there is no milk; both sessions cannot be zero.</p><form onSubmit={submit} className="form"><select name="farmer_id" required><option value="">Select farmer</option>{farmers.map(f=><option value={f.id} key={f.id}>{f.farmer_id} — {f.name}</option>)}</select><input type="date" name="record_date" required/><input type="number" min="0" step="0.5" name="morning_litres" placeholder="Morning litres"/><input type="number" min="0" step="0.5" name="evening_litres" placeholder="Evening litres"/><input name="collector" placeholder="Collector"/><button className="primary">Save Milk Record</button></form></section><section className="panel"><h2>Milk Records</h2><Table headers={["Date","Farmer","Morning","Evening","Total"]} rows={milk.map(m=>[m.record_date,farmers.find(f=>f.id===m.farmer_id)?.name||String(m.farmer_id),`${m.morning_litres} L`,`${m.evening_litres} L`,`${(m.morning_litres+m.evening_litres).toFixed(1)} L`])}/></section></>
}
function Payments({farmers,payments,reload}:{farmers:Farmer[];payments:Payment[];reload:()=>void}){
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/payments",{method:"POST",body:JSON.stringify({farmer_id:Number(f.get("farmer_id")),week_start:f.get("week_start"),week_end:f.get("week_end"),price_per_litre:Number(f.get("price")),deductions:Number(f.get("deductions")||0),payment_date:f.get("payment_date"),method:f.get("method"),reference:f.get("reference")||null})});e.currentTarget.reset();reload()}catch(err){alert(err instanceof Error?err.message:"Error")}};
 return <><section className="panel"><h2>Create Weekly Payment</h2><p className="hint">The system totals milk records inside the selected Monday–Sunday period.</p><form onSubmit={submit} className="form"><select name="farmer_id" required><option value="">Select farmer</option>{farmers.map(f=><option value={f.id} key={f.id}>{f.farmer_id} — {f.name}</option>)}</select><input type="date" name="week_start" required/><input type="date" name="week_end" required/><input type="number" min="0.01" step="0.01" name="price" placeholder="Price per litre (KES)" required/><input type="number" min="0" step="0.01" name="deductions" placeholder="Deductions (KES)"/><input type="date" name="payment_date" required/><select name="method"><option>M-Pesa</option><option>Bank</option><option>Cash</option><option>Other</option></select><input name="reference" placeholder="Payment reference"/><button className="primary">Calculate & Save Payment</button></form></section><section className="panel"><h2>Payments</h2><Table headers={["Farmer","Week","Litres","Gross","Deductions","Net","Method"]} rows={payments.map(p=>[farmers.find(f=>f.id===p.farmer_id)?.name||String(p.farmer_id),`${p.week_start} to ${p.week_end}`,p.litres.toFixed(1),`KES ${p.gross_amount.toFixed(2)}`,`KES ${p.deductions.toFixed(2)}`,`KES ${p.net_amount.toFixed(2)}`,p.method])}/></section></>
}
function Table({headers,rows}:{headers:string[];rows:(string|number)[][]}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}

export default App;
